# This workflow is triggered manually from the Actions tab in GitHub
name: clear

on:
  workflow_dispatch:

permissions:
  contents: write
concurrency:
  group: pages
  cancel-in-progress: true

## from main, it merges with staging
# this file is the only file that is saved(this is executed from main, it merges with staging)
jobs:
  clear_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: delete all but yml
        run: |
          find . -not -name "*.yml" -not -name ".git" -type f -delete
          git commit -m "Merge staging into main"
      - name: Push changes to main
        run: |
          git push origin main
