name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - deployment
  # Allow manual triggering of the workflow


# Set permissions for the GITHUB_TOKEN
permissions: 
  contents: write

# Ensure only one deployment runs at a time
concurrency: 
  group: pages
  cancel-in-progress: true
# Define the jobs to run in this workflow
jobs: 
  tests:
    # The os to run the job on
    runs-on: ubuntu-latest 
    # Steps to execute in the build job
    steps: 
      # Each step is preceded by the - character, and the name of the step is defined by the name key
      - name: Checkout repository
        # The uses key specifies an action to use, in this case, the checkout action to clone the repository
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
  build:
    needs: tests
    # The os to run the job on
    runs-on: ubuntu-latest 
    # Steps to execute in the build job
    steps: 
      # Each step is preceded by the - character, and the name of the step is defined by the name key
      - name: Checkout repository
        # The uses key specifies an action to use, in this case, the checkout action to clone the repository
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      - name: typedoc
        run: npx typedoc

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist
  

        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist
      
      - name: Deploy dist to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          cp -r dist/* .
          git add .
          git commit -m "Deploy dist to main branch"
          git push origin main
