# This workflow is triggered manually from the Actions tab in GitHub
name: Push to Live

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

## from main, it merges with staging
# this file is the only file that is saved(this is executed from main, it merges with staging)
jobs:
  push-to-live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge staging into main
        run: |
          git fetch origin staging
          git merge origin/staging --no-ff -m "Merge staging into main"
      - name: Push changes to main
        run: |
          git push origin main
